
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basics;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int dogCount = 1;
        System.out.println("I own " + dogCount + " " + pluralize("dog", dogCount) + ".");

        int catCount = 2;
        System.out.println("I own " + catCount + " " + pluralize("cat", catCount) + ".");

        int turtleCount = 0;
        System.out.println("I own " + turtleCount + " " + pluralize("turtle", turtleCount) + ".");



        flipNHeads(2);

        timeNow();




    }

    public static String pluralize(String animal , int num){
        if (num > 1 || num == 0){
            return animal+"s";
        }else{
            return animal;
        }
    }

    public static void flipNHeads(int n){
        int counter = 0;
        int head = 0;

        while (head != n){
            double rnd = Math.random();
            if(rnd >= 0.5){
                head+=1;
                counter += 1;
                System.out.println("head");

            }else{
                head=0;
                counter += 1;
                System.out.println("tail");
            }
        }
        System.out.println("It took " + counter + " flips to flip " + n + " head in a row.");

    }

    public static void timeNow() {
        while(true){
            LocalDateTime now = LocalDateTime.now();
            String time = now.format(DateTimeFormatter.ofPattern("HH:mm:ss"));
            System.out.println(time);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}
