/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void testingRestaurantClass(){

        // resturant test without review
        Restaurant testRestaurant = new Restaurant("SubWay",5);
        assertEquals("SubWay",testRestaurant.getName());
        assertEquals(5,testRestaurant.getPriceCat());

        assertEquals("Restaurant{Name='SubWay',Rate out of 5 stars=0.0, Price Category=5.0$, reviews=[]}" , testRestaurant.toString());


        //review test
        Review testReview = new Review("testing", "i love it",4);

        assertEquals("testing ( said: i love it, and rate it with =4.0 stars) ",testReview.toString());


        // addReview method test
        testRestaurant.addReview("humam","i like it",3);
        assertEquals("Restaurant{Name='SubWay',Rate out of 5 stars=3.0, Price Category=5.0$, reviews=[humam ( said: i like it, and rate it with =3.0 stars) ]}" , testRestaurant.toString());





    }

}
