/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static linter.App.*;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testingSplinter(){


        // testing for a no errors js file
        String noErrOut = "";
        Path noErrorFile = Paths.get("src/main/resources/testNoError.js");

        assertEquals(noErrOut,javaScriptLinter(noErrorFile));


        // testing for a one error js file
        String oneErrOut = "Line 3: Missing semicolon.\n";
        Path oneErrorFile = Paths.get("src/main/resources/testOneError.js");

        assertEquals(oneErrOut,javaScriptLinter(oneErrorFile));



        // testing for a one error js file
        String someErrOut = "Line 3: Missing semicolon.\n"+"Line 5: Missing semicolon.\n";
        Path someErrorsFile = Paths.get("src/main/resources/testSomeError.js");

        assertEquals(someErrOut,javaScriptLinter(someErrorsFile));



    }
}
